// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8tIOiEPIMiPUA0Mx_HMCsojN2LatJ4Q4',
    appId: '1:754472506810:web:b888c93d7ef234d0ae3983',
    messagingSenderId: '754472506810',
    projectId: 'ownnotes',
    authDomain: 'ownnotes.firebaseapp.com',
    storageBucket: 'ownnotes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt9BH8b0Po73AkIbFaIkGUpo8ABA-56XY',
    appId: '1:754472506810:android:acd0815777631afbae3983',
    messagingSenderId: '754472506810',
    projectId: 'ownnotes',
    storageBucket: 'ownnotes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0yOKCOTv3EcD0ayAFqAc54AgMblgOiX0',
    appId: '1:754472506810:ios:ff7fb814fe34f523ae3983',
    messagingSenderId: '754472506810',
    projectId: 'ownnotes',
    storageBucket: 'ownnotes.appspot.com',
    iosBundleId: 'com.stephenprojects.ownnotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0yOKCOTv3EcD0ayAFqAc54AgMblgOiX0',
    appId: '1:754472506810:ios:38064419d10ca9d2ae3983',
    messagingSenderId: '754472506810',
    projectId: 'ownnotes',
    storageBucket: 'ownnotes.appspot.com',
    iosBundleId: 'com.stephenprojects.ownnotes.RunnerTests',
  );
}
